### ISSUE TITLE
[FEATURE] Inheriting `X-Request-Id` header value

### ISSUE THREAD

**Issue by Sija** [Baboo7/strapi-plugin-request-id#1]
Hi,

Thanks for your work on this plugin! I wanted to use it along with AWS request tracing, but because the header value gets generated by the plugin itself, the trace won't match the ids used before, so that won't work :(

Could `X-Request-Id` header be generated only if it's not being already given from the downstream?

**Comment by Baboo7** [comment]
The `X-Request-Id` header is used to track users actions on one server only, not across services. For your purpose, I would use the `X-Correlation-Id` header instead (see the [Usage](https://github.com/Baboo7/strapi-plugin-request-id#usage) part of the doc). `X-Correlation-Id` is generated only if not provided (whereas `X-Request-Id` can't be specified manually atm).
 
I guess the option could be added as a plugin config param to explicitly allow the rewriting of the `X-Request-Id` header.

**Comment by Sija** [comment]
Amazon's ALB uses [`X-Amzn-Trace-Id`](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html) header for instance.

An option to allow configuring this would be great, something along `request_id_header: "X-Amzn-Trace-Id"` which would then check for the header existence and if not present it would generate the id as usual.

**Comment by Baboo7** [comment]
I just pushed version `1.1.0`.
I went for the configuration of the `correlation id` instead but the feature works the same.

You can now customize the `correlation id` header:

```js
"request-id": {
  enabled: true,
  config: {
    correlationIdHeader: "X-Amzn-Trace-Id",
  },
},
```

You can find a more detailed example in the [Examples section](https://github.com/Baboo7/strapi-plugin-request-id#example-3-customize-the-correlation-id-header) of the doc.

**Comment by Sija** [comment]
Yeah... but it's the `X-Request-Id` specifically that's needed.

**Comment by Sija** [comment]
See the [`Plug.RequestId`](https://hexdocs.pm/plug/Plug.RequestId.html#module-options) or [`Sentry.PlugContext`](https://hexdocs.pm/sentry/8.0.6/Sentry.PlugContext.html#module-including-request-identifiers) for Pheonix framework as an examples.

**Comment by Baboo7** [comment]
I will have a look.

To better understand your use case, you want to customize the request id using the the header `X-Amzn-Trace-Id` if it exists, and return the header `X-Request-Id`?

**Comment by Sija** [comment]
I informed myself re: the difference between those and now I think you've chosen the correct approach. Sorry for not checking that earlier! 🤦‍♂️

**Comment by Baboo7** [comment]
No worries. I'm glad it fits your needs 😌
