### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by serhiinkh** [Baboo7/strapi-plugin-request-id#3]
Hello, in Strapi docs they saying that Node v18.x is recommended version.

<img width="977" alt="Screenshot 2023-02-08 at 22 39 34" src="https://user-images.githubusercontent.com/2728287/217646048-c9c3bbcb-35dd-42ec-bb5c-ae2bad952a9d.png">

**Comment by Baboo7** [comment]
@serhiinkh version `1.2.0` is available and adds the support for node `18` in `package.json`. It should be all good on your side
